In [6]:
import numpy as np

In [8]:
array_one = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [11]:
numbers = [9,8,7,6]
array_two = np.array(numbers)
array_two

array([9, 8, 7, 6])

In [13]:
array_of_zeros = np.zeros((3,4))
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])